source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'
use_frameworks!

target 'RocketNetwork_Example' do
  pod 'RocketNetwork', :path => '../'

  target 'RocketNetwork_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
